[package]
name = "overlay-bn"
description = "The link to the local Lighthouse beacon node: gossipsub, req/resp, HTTP API."
version.workspace = true
edition.workspace = true

[dependencies]
libp2p.workspace = true
overlay-core.workspace = true

[dev-dependencies]
lighthouse_network.workspace = true
tempfile.workspace = true
types.workspace = true

[lints]
workspace = true
