//! Every message the overlay puts on a QUIC connection, and the two carriers that move them.
//!
//! The layout is hand-rolled little-endian rather than a serialisation framework, because it is
//! small, has to stay readable in a packet capture, and has to decode byte for byte under every
//! later release. `crates/overlay-core/tests/vectors/v1` holds one file per variant and is what
//! proves that; the files are generated by `examples/gen_vectors.rs` and never edited by hand.
//!
//! Every frame starts with `type: u8, flags: u8`. Senders zero the flag bits they do not define
//! and receivers drop the bits they do not know, so a release that defines a new bit still talks
//! to one that has never heard of it. Fixed-field layouts never change after a release: new data
//! goes in a new frame type, or behind a feature bit HELLO negotiates (D10, D11, D29).
//!
//! `str16` is a `u16` length and UTF-8 bytes; `bytes16` and `bytes32` are a `u16` or `u32` length
//! and that many bytes. Every integer is little-endian.
//!
//! | Frame | type | flags | Body after `type, flags` |
//! |---|---|---|---|
//! | `HELLO` | 1 | none | `minor: u16`, `features: u64`, `max_frame_bytes: u32`, `max_batch_entries: u16`, `instance_id: u64`, `hostname: str16`, `region: str16`, `site: str16`, `software_version: str16`, `topics: u16 count` then `(id: u16, topic: str16)` |
//! | `SUBS` | 2 | none | `bitmap: bytes16` |
//! | `TOPIC_ADD` | 3 | none | `id: u16`, `topic: str16` |
//! | `BATCH` | 4 | bit 0 `RELAY` | `count: u16` then entries `(topic_id: u16, len: u16, payload)` |
//! | `CHUNK` | 5 | bit 0 `FORWARDED` | `msg_id: [u8; 20]`, `topic_id: u16`, `k: u16`, `m: u16`, `index: u16`, `total_len: u32`, `data: bytes32` |
//! | `HAVE` | 6 | | reserved, never encoded; decodes as an unknown type |
//! | `REPAIR_REQ` | 7 | none | `tag: u8`; 0 → `msg_id: [u8; 20]`, `missing: u16 count` then `u16` indices (data indices first); 1 → `block_root: [u8; 32]`, `index: u8` |
//! | `REPAIR_RESP` | 8 | none | `tag: u8`; 0 → not found; 1 → `count: u16` then `count` CHUNK bodies (a whole message is one `k = 1` chunk) |
//!
//! # Carriers
//!
//! A stream prefixes each frame with a `u32` length and carries several one after another; a
//! datagram carries exactly one frame and no prefix. The codec itself is carrier-agnostic, so the
//! two skip rules live in the helpers: on a stream an unknown type is consumed and reported, and
//! the caller counts it and reads on; in a datagram it is an error, and the caller drops the
//! datagram. Trailing bytes in a datagram are an error for the same reason: a frame that grew a
//! field would otherwise be indistinguishable from a truncated one.
//!
//! # Chunks carry a whole message too
//!
//! A `CHUNK` header is self-describing, so a receiver reassembles without knowing who was sent
//! what (§5.4). The same layout with `k = 1, m = 0` is how an unsplit message travels: v1's direct
//! fanout (T-032) and the fallback toward a peer that advertised neither `STRIPING` nor
//! `DATAGRAM_BATCHES` both use it, and so does a `REPAIR_RESP`. `BATCH` cannot: its entries carry
//! a `u16` length, which a block does not fit in (D21).

use bytes::{Buf, BufMut, Bytes, BytesMut};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};

use crate::msgid::MessageId;
use crate::protocol::MAX_BATCH_ENTRIES;

/// The most a gossipsub payload decompresses to, and so the most any one frame can carry. The
/// number is the consensus spec's `MAX_PAYLOAD_SIZE` for mainnet, which is what the beacon node
/// enforces on the way in; it is repeated here because the dependency runs from `overlay-bn` to
/// `overlay-core` and not the other way, and `overlay_bn::gossip::wire`'s drift test asserts this
/// constant equals the value read out of Lighthouse.
pub const MAX_PAYLOAD_BYTES: usize = 10_485_760;

/// The longest topic string a `TOPIC_ADD` or a HELLO snapshot may name. Real topics are around
/// fifty bytes, so this is room for a fork digest and a name nobody has invented yet rather than a
/// figure to tune.
pub const MAX_TOPIC_BYTES: usize = 256;

/// The most indices one `REPAIR_REQ` may ask for. A message is at most `MAX_PAYLOAD_BYTES` of
/// 2 KiB chunks, so a request past this is asking for something that cannot exist.
pub const MAX_MISSING_INDICES: usize = 4096;

/// The most topics one HELLO may announce. A beacon node subscribes to a few hundred topics
/// across a fork transition; this leaves room for several forks at once.
pub const MAX_TOPIC_SNAPSHOT_ENTRIES: usize = 4096;

/// The flag bits a `CHUNK` defines.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ChunkFlags(u8);

impl ChunkFlags {
    /// No flags set, which is how a chunk leaves the host the message came from.
    pub const NONE: Self = Self(0);

    /// The chunk is the in-region second hop and is never forwarded again (D11, D19).
    pub const FORWARDED: Self = Self(1);

    /// Keeps only the bits this release defines. A peer that learns a new bit can set it and
    /// still be understood here.
    pub fn from_bits_truncate(bits: u8) -> Self {
        Self(bits & Self::FORWARDED.0)
    }

    /// The byte that goes on the wire, with every undefined bit zero.
    pub fn bits(self) -> u8 {
        self.0
    }

    /// Whether every bit of `other` is set.
    pub fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// The flag bits a `BATCH` defines.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BatchFlags(u8);

impl BatchFlags {
    /// No flags set, which is what a batch sent directly to its destination carries.
    pub const NONE: Self = Self(0);

    /// The receiver is asked to fan the batch out inside its own region (D11, D20).
    pub const RELAY: Self = Self(1);

    /// Keeps only the bits this release defines. A peer that learns a new bit can set it and
    /// still be understood here.
    pub fn from_bits_truncate(bits: u8) -> Self {
        Self(bits & Self::RELAY.0)
    }

    /// The byte that goes on the wire, with every undefined bit zero.
    pub fn bits(self) -> u8 {
        self.0
    }

    /// Whether every bit of `other` is set.
    pub fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// The type byte, including the one no [`Frame`] variant exists for. The numbers are the wire
/// protocol and are assigned once.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FrameType {
    /// [`Frame::Hello`].
    Hello = 1,
    /// [`Frame::Subs`].
    Subs = 2,
    /// [`Frame::TopicAdd`].
    TopicAdd = 3,
    /// [`Frame::Batch`].
    Batch = 4,
    /// [`Frame::Chunk`].
    Chunk = 5,
    /// Reserved and never sent. Repair candidates come from which peer sent which chunk, so the
    /// announcement this id was meant for does not exist (D23); the id stays taken so a later
    /// release cannot reuse it for something a v1 peer would misread.
    Have = 6,
    /// [`Frame::RepairReq`].
    RepairReq = 7,
    /// [`Frame::RepairResp`].
    RepairResp = 8,
}

impl FrameType {
    /// The type this byte names, or `None` for one no release has defined.
    pub fn from_u8(byte: u8) -> Option<Self> {
        match byte {
            1 => Some(Self::Hello),
            2 => Some(Self::Subs),
            3 => Some(Self::TopicAdd),
            4 => Some(Self::Batch),
            5 => Some(Self::Chunk),
            6 => Some(Self::Have),
            7 => Some(Self::RepairReq),
            8 => Some(Self::RepairResp),
            _ => None,
        }
    }

    /// The byte that goes on the wire.
    pub fn id(self) -> u8 {
        self as u8
    }
}

/// What one end of a connection tells the other before anything else (D29, D15). The limits and
/// the feature bits are the peer's, not this host's: a sender never exceeds them and never uses a
/// behaviour the peer did not advertise.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Hello {
    /// The protocol minor the sender speaks. A pair operates at the lower of the two.
    pub minor: u16,
    /// The feature bits the sender supports, from [`crate::protocol::features`]. A pair operates
    /// at the intersection.
    pub features: u64,
    /// The largest frame the sender will accept on a stream.
    pub max_frame_bytes: u32,
    /// The most entries the sender will accept in one `BATCH`.
    pub max_batch_entries: u16,
    /// Random per process start, so a supersede (D15) can say whether the peer restarted or its
    /// path changed.
    pub instance_id: u64,
    /// The sender's roster hostname, cross-checked against the key its TLS handshake pinned.
    pub hostname: String,
    /// The region the sender fans out in. Recorded even when it disagrees with the roster (D15).
    pub region: String,
    /// The sender's site, a label for metrics and failure-domain reporting only.
    pub site: String,
    /// The sender's `CARGO_PKG_VERSION`, for `fleet-overlayctl status` and upgrade reporting.
    pub software_version: String,
    /// The sender's whole topic table, as `(id, topic)`, so ids reach the peer before any payload
    /// on them (§5.4).
    pub topics: Vec<(u16, String)>,
}

/// One payload inside a `BATCH`. Each entry names its own topic, so one batch mixes topics and a
/// topic id the receiver does not know costs that entry alone (D21).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BatchEntry {
    /// The sender's id for the topic.
    pub topic_id: u16,
    /// The gossipsub wire form, snappy-compressed SSZ, which the overlay never looks inside.
    pub payload: Bytes,
}

/// One piece of a message, or a whole one when `k = 1, m = 0`. Everything a receiver needs to
/// reassemble is in the header, so two origins with different views of the fleet still produce
/// chunks that fit together (§5.4).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Chunk {
    /// The gossipsub message id, which is what dedupes and what a repair request names.
    pub msg_id: MessageId,
    /// The sender's id for the topic the message arrived on.
    pub topic_id: u16,
    /// How many data chunks the message was split into. At least one.
    pub k: u16,
    /// How many parity chunks follow them.
    pub m: u16,
    /// This chunk's index, below `k + m`; the first `k` are data.
    pub index: u16,
    /// The whole message's length, which is what tells a receiver when it is done.
    pub total_len: u32,
    /// This chunk's bytes.
    pub data: Bytes,
}

impl Chunk {
    /// Whether this chunk is the whole message rather than a piece of one.
    pub fn is_whole(&self) -> bool {
        self.k == 1 && self.m == 0
    }

    fn validate(&self) -> Result<(), DecodeError> {
        if self.k == 0 {
            return Err(DecodeError::Invalid("k"));
        }
        if u32::from(self.index) >= u32::from(self.k) + u32::from(self.m) {
            return Err(DecodeError::Invalid("index"));
        }
        if self.total_len as usize > MAX_PAYLOAD_BYTES {
            return Err(DecodeError::OverLimit("total_len"));
        }
        if self.is_whole() && self.data.len() != self.total_len as usize {
            return Err(DecodeError::Invalid("whole"));
        }
        Ok(())
    }
}

/// What a repair asks for (D23, D24).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RepairReq {
    /// Indices of a message already in flight, data indices first so a responder that can only
    /// serve some of them serves the ones that avoid a decode.
    Missing {
        /// The message the indices belong to.
        msg_id: MessageId,
        /// The indices still wanted.
        missing: Vec<u16>,
    },
    /// A custody column by identity, for a block whose chunks never arrived at all (T-083).
    Column {
        /// The block the column belongs to.
        block_root: [u8; 32],
        /// The column index.
        index: u8,
    },
}

/// The answer to a [`RepairReq`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RepairResp {
    /// The responder does not hold it, and the requester moves on to the next candidate.
    NotFound,
    /// The chunks it does hold, a whole message being one chunk with `k = 1`.
    Chunks(Vec<Chunk>),
}

/// Everything the overlay sends. `HAVE` has no variant: it is reserved and never encoded.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Frame {
    /// The first frame on the first bidi stream of a connection.
    Hello(Hello),
    /// The sender's whole subscription bitmap, resent on every change.
    Subs {
        /// One bit per subscribable topic, in the order T-027 fixes.
        bitmap: Bytes,
    },
    /// One more topic string bound to one more id, sent when the local set grows.
    TopicAdd {
        /// The sender's id for the topic.
        id: u16,
        /// The topic string.
        topic: String,
    },
    /// Small-class payloads for one destination, mixing topics.
    Batch {
        /// `RELAY` asks the receiver to fan the batch out in its own region.
        flags: BatchFlags,
        /// The payloads, each with its own topic id.
        entries: Vec<BatchEntry>,
    },
    /// One piece of a large message, or a whole message.
    Chunk {
        /// `FORWARDED` marks the in-region second hop.
        flags: ChunkFlags,
        /// The self-describing chunk.
        chunk: Chunk,
    },
    /// A request for chunks a receiver is missing.
    RepairReq(RepairReq),
    /// The answer to one.
    RepairResp(RepairResp),
}

/// Why a frame did not decode.
#[derive(Clone, Copy, Debug, PartialEq, Eq, thiserror::Error)]
pub enum DecodeError {
    /// The bytes ran out mid-frame.
    #[error("frame ended early")]
    Truncated,
    /// A type byte no release has defined, or the reserved `HAVE`. The caller decides what to do
    /// with it, which differs between the two carriers.
    #[error("unknown frame type {0}")]
    UnknownType(u8),
    /// A count or a length past what this release accepts, named by the field.
    #[error("{0} is over the limit")]
    OverLimit(&'static str),
    /// A field the layout allows but the frame's own rules do not, named by the field.
    #[error("invalid {0}")]
    Invalid(&'static str),
}

impl Frame {
    /// A whole message in the chunk layout: one data chunk, no parity, `total_len` the payload's
    /// own length. The payload must be within [`MAX_PAYLOAD_BYTES`], which is what the beacon node
    /// already enforced on it.
    pub fn whole_message(msg_id: MessageId, topic_id: u16, payload: Bytes) -> Self {
        Self::Chunk {
            flags: ChunkFlags::NONE,
            chunk: Chunk {
                msg_id,
                topic_id,
                k: 1,
                m: 0,
                index: 0,
                total_len: payload.len() as u32,
                data: payload,
            },
        }
    }

    /// The type byte this frame carries.
    pub fn frame_type(&self) -> FrameType {
        match self {
            Self::Hello(_) => FrameType::Hello,
            Self::Subs { .. } => FrameType::Subs,
            Self::TopicAdd { .. } => FrameType::TopicAdd,
            Self::Batch { .. } => FrameType::Batch,
            Self::Chunk { .. } => FrameType::Chunk,
            Self::RepairReq(_) => FrameType::RepairReq,
            Self::RepairResp(_) => FrameType::RepairResp,
        }
    }

    fn flag_bits(&self) -> u8 {
        match self {
            Self::Batch { flags, .. } => flags.bits(),
            Self::Chunk { flags, .. } => flags.bits(),
            _ => 0,
        }
    }

    /// Appends the frame, header and body, with no length prefix. Fields have to be within the
    /// limits this module documents; a value built past them encodes a length the decoder refuses.
    pub fn encode(&self, out: &mut BytesMut) {
        out.put_u8(self.frame_type().id());
        out.put_u8(self.flag_bits());
        match self {
            Self::Hello(hello) => {
                out.put_u16_le(hello.minor);
                out.put_u64_le(hello.features);
                out.put_u32_le(hello.max_frame_bytes);
                out.put_u16_le(hello.max_batch_entries);
                out.put_u64_le(hello.instance_id);
                put_str16(out, &hello.hostname);
                put_str16(out, &hello.region);
                put_str16(out, &hello.site);
                put_str16(out, &hello.software_version);
                out.put_u16_le(hello.topics.len() as u16);
                for (id, topic) in &hello.topics {
                    out.put_u16_le(*id);
                    put_str16(out, topic);
                }
            }
            Self::Subs { bitmap } => {
                out.put_u16_le(bitmap.len() as u16);
                out.put_slice(bitmap);
            }
            Self::TopicAdd { id, topic } => {
                out.put_u16_le(*id);
                put_str16(out, topic);
            }
            Self::Batch { entries, .. } => {
                out.put_u16_le(entries.len() as u16);
                for entry in entries {
                    out.put_u16_le(entry.topic_id);
                    out.put_u16_le(entry.payload.len() as u16);
                    out.put_slice(&entry.payload);
                }
            }
            Self::Chunk { chunk, .. } => put_chunk(out, chunk),
            Self::RepairReq(RepairReq::Missing { msg_id, missing }) => {
                out.put_u8(0);
                out.put_slice(&msg_id.0);
                out.put_u16_le(missing.len() as u16);
                for index in missing {
                    out.put_u16_le(*index);
                }
            }
            Self::RepairReq(RepairReq::Column { block_root, index }) => {
                out.put_u8(1);
                out.put_slice(block_root);
                out.put_u8(*index);
            }
            Self::RepairResp(RepairResp::NotFound) => out.put_u8(0),
            Self::RepairResp(RepairResp::Chunks(chunks)) => {
                out.put_u8(1);
                out.put_u16_le(chunks.len() as u16);
                for chunk in chunks {
                    put_chunk(out, chunk);
                }
            }
        }
    }

    /// Reads one frame, leaving whatever follows it in `buf`. Undefined flag bits are dropped, and
    /// every read checks what is left first, so a truncated frame is [`DecodeError::Truncated`]
    /// rather than a panic.
    pub fn decode(buf: &mut Bytes) -> Result<Self, DecodeError> {
        let type_byte = read_u8(buf)?;
        let flag_bits = read_u8(buf)?;
        let Some(frame_type) = FrameType::from_u8(type_byte) else {
            return Err(DecodeError::UnknownType(type_byte));
        };

        match frame_type {
            FrameType::Hello => {
                let minor = read_u16(buf)?;
                let features = read_u64(buf)?;
                let max_frame_bytes = read_u32(buf)?;
                let max_batch_entries = read_u16(buf)?;
                let instance_id = read_u64(buf)?;
                let hostname = read_str16(buf, u16::MAX as usize)?;
                let region = read_str16(buf, u16::MAX as usize)?;
                let site = read_str16(buf, u16::MAX as usize)?;
                let software_version = read_str16(buf, u16::MAX as usize)?;
                let count = read_u16(buf)? as usize;
                if count > MAX_TOPIC_SNAPSHOT_ENTRIES {
                    return Err(DecodeError::OverLimit("topics"));
                }
                let mut topics = Vec::with_capacity(count);
                for _ in 0..count {
                    let id = read_u16(buf)?;
                    topics.push((id, read_str16(buf, MAX_TOPIC_BYTES)?));
                }
                Ok(Self::Hello(Hello {
                    minor,
                    features,
                    max_frame_bytes,
                    max_batch_entries,
                    instance_id,
                    hostname,
                    region,
                    site,
                    software_version,
                    topics,
                }))
            }
            FrameType::Subs => {
                let len = read_u16(buf)? as usize;
                Ok(Self::Subs {
                    bitmap: read_bytes(buf, len)?,
                })
            }
            FrameType::TopicAdd => {
                let id = read_u16(buf)?;
                Ok(Self::TopicAdd {
                    id,
                    topic: read_str16(buf, MAX_TOPIC_BYTES)?,
                })
            }
            FrameType::Batch => {
                let count = read_u16(buf)?;
                if count > MAX_BATCH_ENTRIES {
                    return Err(DecodeError::OverLimit("entries"));
                }
                let mut entries = Vec::with_capacity(count as usize);
                for _ in 0..count {
                    let topic_id = read_u16(buf)?;
                    let len = read_u16(buf)? as usize;
                    entries.push(BatchEntry {
                        topic_id,
                        payload: read_bytes(buf, len)?,
                    });
                }
                Ok(Self::Batch {
                    flags: BatchFlags::from_bits_truncate(flag_bits),
                    entries,
                })
            }
            FrameType::Chunk => Ok(Self::Chunk {
                flags: ChunkFlags::from_bits_truncate(flag_bits),
                chunk: read_chunk(buf)?,
            }),
            FrameType::Have => Err(DecodeError::UnknownType(type_byte)),
            FrameType::RepairReq => match read_u8(buf)? {
                0 => {
                    let msg_id = MessageId(read_array(buf)?);
                    let count = read_u16(buf)? as usize;
                    if count > MAX_MISSING_INDICES {
                        return Err(DecodeError::OverLimit("missing"));
                    }
                    let mut missing = Vec::with_capacity(count);
                    for _ in 0..count {
                        missing.push(read_u16(buf)?);
                    }
                    Ok(Self::RepairReq(RepairReq::Missing { msg_id, missing }))
                }
                1 => {
                    let block_root = read_array(buf)?;
                    Ok(Self::RepairReq(RepairReq::Column {
                        block_root,
                        index: read_u8(buf)?,
                    }))
                }
                _ => Err(DecodeError::Invalid("tag")),
            },
            FrameType::RepairResp => match read_u8(buf)? {
                0 => Ok(Self::RepairResp(RepairResp::NotFound)),
                1 => {
                    let count = read_u16(buf)?;
                    let mut chunks = Vec::new();
                    for _ in 0..count {
                        chunks.push(read_chunk(buf)?);
                    }
                    Ok(Self::RepairResp(RepairResp::Chunks(chunks)))
                }
                _ => Err(DecodeError::Invalid("tag")),
            },
        }
    }
}

fn put_str16(out: &mut BytesMut, value: &str) {
    out.put_u16_le(value.len() as u16);
    out.put_slice(value.as_bytes());
}

fn put_chunk(out: &mut BytesMut, chunk: &Chunk) {
    out.put_slice(&chunk.msg_id.0);
    out.put_u16_le(chunk.topic_id);
    out.put_u16_le(chunk.k);
    out.put_u16_le(chunk.m);
    out.put_u16_le(chunk.index);
    out.put_u32_le(chunk.total_len);
    out.put_u32_le(chunk.data.len() as u32);
    out.put_slice(&chunk.data);
}

fn read_bytes(buf: &mut Bytes, len: usize) -> Result<Bytes, DecodeError> {
    if buf.remaining() < len {
        return Err(DecodeError::Truncated);
    }
    Ok(buf.split_to(len))
}

fn read_array<const N: usize>(buf: &mut Bytes) -> Result<[u8; N], DecodeError> {
    let mut out = [0u8; N];
    out.copy_from_slice(&read_bytes(buf, N)?);
    Ok(out)
}

fn read_u8(buf: &mut Bytes) -> Result<u8, DecodeError> {
    Ok(read_array::<1>(buf)?[0])
}

fn read_u16(buf: &mut Bytes) -> Result<u16, DecodeError> {
    Ok(u16::from_le_bytes(read_array(buf)?))
}

fn read_u32(buf: &mut Bytes) -> Result<u32, DecodeError> {
    Ok(u32::from_le_bytes(read_array(buf)?))
}

fn read_u64(buf: &mut Bytes) -> Result<u64, DecodeError> {
    Ok(u64::from_le_bytes(read_array(buf)?))
}

fn read_str16(buf: &mut Bytes, max: usize) -> Result<String, DecodeError> {
    let len = read_u16(buf)? as usize;
    if len > max {
        return Err(DecodeError::OverLimit("string"));
    }
    let bytes = read_bytes(buf, len)?;
    String::from_utf8(bytes.to_vec()).map_err(|_| DecodeError::Invalid("utf8"))
}

/// The length is checked against the limit before the bytes are taken, so an oversized frame costs
/// nothing to refuse.
fn read_chunk(buf: &mut Bytes) -> Result<Chunk, DecodeError> {
    let msg_id = MessageId(read_array(buf)?);
    let topic_id = read_u16(buf)?;
    let k = read_u16(buf)?;
    let m = read_u16(buf)?;
    let index = read_u16(buf)?;
    let total_len = read_u32(buf)?;
    let len = read_u32(buf)? as usize;
    if len > MAX_PAYLOAD_BYTES {
        return Err(DecodeError::OverLimit("data"));
    }
    let chunk = Chunk {
        msg_id,
        topic_id,
        k,
        m,
        index,
        total_len,
        data: read_bytes(buf, len)?,
    };
    chunk.validate()?;
    Ok(chunk)
}

/// What one stream read produced. An unknown type is not an error on a stream: the frame is
/// consumed, the caller counts `unknown_frame_type_total{peer}` and keeps reading, which is what
/// lets a newer peer send frames this release has never heard of (D10).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Read {
    /// A frame this release understands.
    Frame(Frame),
    /// The type byte of one it does not.
    Unknown(u8),
}

/// Why a stream read did not produce a frame.
#[derive(Debug, thiserror::Error)]
pub enum ReadError {
    /// The length prefix is past the maximum the peer agreed to in HELLO. Nothing was read after
    /// it, so the caller closes rather than resynchronising.
    #[error("frame of {0} bytes is over the agreed maximum")]
    TooLarge(u32),
    /// The frame arrived whole and did not decode.
    #[error("frame body: {0}")]
    Decode(#[from] DecodeError),
    /// The stream ended or failed.
    #[error("stream: {0}")]
    Io(#[from] std::io::Error),
}

/// Writes one frame with its `u32` length prefix. The prefix and the body go out in one write, so
/// a reader never sees half a frame's worth of a partial write.
pub async fn write_frame<W>(stream: &mut W, frame: &Frame) -> std::io::Result<()>
where
    W: AsyncWrite + Unpin,
{
    let mut out = BytesMut::new();
    out.put_u32_le(0);
    frame.encode(&mut out);
    let len = (out.len() - 4) as u32;
    out[..4].copy_from_slice(&len.to_le_bytes());
    stream.write_all(&out).await
}

/// Reads one frame. The length prefix is checked against `max_frame_bytes` before anything is
/// allocated for the body, so a peer cannot make this host reserve memory by lying about a size.
pub async fn read_frame<R>(stream: &mut R, max_frame_bytes: u32) -> Result<Read, ReadError>
where
    R: AsyncRead + Unpin,
{
    let mut prefix = [0u8; 4];
    stream.read_exact(&mut prefix).await?;
    let len = u32::from_le_bytes(prefix);
    if len > max_frame_bytes {
        return Err(ReadError::TooLarge(len));
    }

    let mut body = vec![0u8; len as usize];
    stream.read_exact(&mut body).await?;

    match Frame::decode(&mut Bytes::from(body)) {
        Ok(frame) => Ok(Read::Frame(frame)),
        Err(DecodeError::UnknownType(id)) => Ok(Read::Unknown(id)),
        Err(error) => Err(ReadError::Decode(error)),
    }
}

/// One frame as a datagram: the same bytes as on a stream, without the length prefix, because the
/// datagram is the frame.
pub fn encode_datagram(frame: &Frame) -> Bytes {
    let mut out = BytesMut::new();
    frame.encode(&mut out);
    out.freeze()
}

/// Reads the one frame a datagram carries. Anything left over is an error, and so is an unknown
/// type: the caller drops the whole datagram either way (D10).
pub fn decode_datagram(datagram: Bytes) -> Result<Frame, DecodeError> {
    let mut buf = datagram;
    let frame = Frame::decode(&mut buf)?;
    if buf.has_remaining() {
        return Err(DecodeError::Invalid("trailing"));
    }
    Ok(frame)
}
